sudo: required

language: c

env:
  global:
    - GAPCONTAINER="gapsystem/gap-docker-stable-4.10"
    - GAPDIRNAME="gap-stable-4.10"

  matrix:
    - REPO_URL=https://github.com/gap-packages/4ti2gap
    - REPO_URL=https://github.com/gap-packages/ace # GAP interface for the the Advanced Coset Enumerator (ACE)
    - REPO_URL=https://github.com/gap-packages/aclib # Almost Crystallographic Groups - A Library and Algorithms
    - REPO_URL=https://github.com/gap-packages/alnuth # ALgebraic NUmber THeory for GAP
    - REPO_URL=https://github.com/gap-packages/anupq # The ANUPQ GAP package
    - REPO_URL=https://github.com/gap-packages/autodoc # A GAP Package to produce documentations
    - REPO_URL=https://github.com/gap-packages/automata # A GAP package on automata
    - REPO_URL=https://github.com/gap-packages/autpgrp # Computing the Automorphism Group of a p-Group
    - REPO_URL=https://github.com/gap-packages/biogap # GAP package for abstract algebraic algorithms in phylogeny (bacterial genomics)
    - REPO_URL=https://github.com/gap-packages/carat # Interface to CARAT, a crystallographic groups package
    - REPO_URL=https://github.com/gap-packages/Char0Gauss # Linear algebra stuff
    - REPO_URL=https://github.com/gap-packages/circle # Adjoint groups of finite rings
    - REPO_URL=https://github.com/gap-packages/cohomolo # Cohomology groups of finite groups on finite modules
    - REPO_URL=https://github.com/gap-packages/congruence # Congruence subgroups of SL(2,Integers)
    - REPO_URL=https://github.com/gap-packages/crime
    - REPO_URL=https://github.com/bh11/crisp
    - REPO_URL=https://github.com/gap-packages/crypting # Hashes and Crypto in GAP
    - REPO_URL=https://github.com/gap-packages/cryst # Computing with crystallographic groups
    - REPO_URL=https://github.com/gap-packages/crystcat # The crystallographic groups catalog
    - REPO_URL=https://github.com/gap-packages/curlInterface # Easy web access for GAP
    - REPO_URL=https://github.com/gap-packages/cvec # GAP package for Compressed vectors and matrices over finite fields
    - REPO_URL=https://github.com/gap-packages/datastructures # Package for Standard Datastructures for (HPC-)GAP
    - REPO_URL=https://github.com/gap-packages/debugger # Debugging and Breakpoints for GAP
    - REPO_URL=https://github.com/duskydolphin/DeepThoughtPackage
    - REPO_URL=https://github.com/gap-packages/design
    - REPO_URL=https://github.com/dylanpeifer/difsets
    - REPO_URL=https://github.com/gap-packages/Digraphs # The GAP package Digraphs
    - REPO_URL=https://github.com/frankluebeck/EDIM
    - REPO_URL=https://github.com/gap-packages/example # GAP Example Package
    - REPO_URL=https://github.com/gap-packages/FactInt # FactInt -- Advanced Methods for [Fact]oring [Int]egers
    - REPO_URL=https://github.com/gap-packages/ferret # GAP package for searching in finite permutation groups
    - REPO_URL=https://github.com/chsievers/fga
    - REPO_URL=https://bitbucket.org/jdebeule/fining
    - REPO_URL=https://github.com/gap-packages/float # GAP package for floating-point support in GAP
    - REPO_URL=https://github.com/gap-packages/format # Computing with formations of finite solvable groups
    # - REPO_URL=https://bitbucket.org/jdebeule/forms # This is mercurial repository
    - REPO_URL=https://github.com/gap-packages/FPLSA # A GAP package which implements the Lie Todd-Coxeter method for converting finitely presented Lie algebras into isomorphic structure constant algebras
    - REPO_URL=https://github.com/gap-packages/fr # GAP package for functionally recursive (automata) groups in GAP
    - REPO_URL=https://github.com/gap-packages/FrancyMonoids # Finitely Generated Commutative Monoids and Francy
    - REPO_URL=https://github.com/nzidaric/fsr
    - REPO_URL=https://github.com/gap-packages/GaloisGroups # Computing Galois Groups in GAP
    - REPO_URL=https://github.com/gap-packages/gapbench # Some benchmarks for the GAP system.
    - REPO_URL=https://github.com/gap-packages/GAPQuickcheck # Library for property testing in GAP
    - REPO_URL=https://github.com/gap-packages/genss # The GAP package genss for randomised Schreier-Sims
    - REPO_URL=https://github.com/gap-packages/grape
    - REPO_URL=https://github.com/gap-packages/groupoids # GAP package groupoids (algorithms for finite groupoids) 
    - REPO_URL=https://github.com/gap-packages/grpconst # Constructing the Groups of a Given Order
    - REPO_URL=https://github.com/gap-packages/guarana # Applications of Lie methods for computations with infinite polycyclic groups
    - REPO_URL=https://github.com/gap-packages/guava # GAP package guava - computations relative to error-correcting codes
    - REPO_URL=https://github.com/gap-packages/hecke # Decomposition matrices of Hecke algebras of the symmetric groups and q-Schur algebras
    - REPO_URL=https://github.com/gap-packages/idrel # GAP package IdRel 
    - REPO_URL=https://github.com/gap-packages/images # GAP package for computing minimal and canonical images
    - REPO_URL=https://github.com/gap-packages/img # Iterated monodromy groups in GAP
    - REPO_URL=https://github.com/gap-packages/intpic # A GAP package for drawing integers
    - REPO_URL=https://github.com/gap-packages/io # GAP package IO to do input and output
    - REPO_URL=https://github.com/bh11/irredsol
    - REPO_URL=https://github.com/gap-packages/json # A GAP Package for reading and writing JSON
    - REPO_URL=https://github.com/gap-packages/JupyterKernel # Native Jupyter kernel for GAP
    - REPO_URL=https://github.com/gap-packages/kan # GAP package kan 
    - REPO_URL=https://github.com/gap-packages/kbmag # Knuth-Bendix on Monoids and Automatic Groups
    - REPO_URL=https://github.com/gap-packages/kerneltest 
    - REPO_URL=https://github.com/gap-packages/laguna # Lie AlGebras and UNits of group Algebras
    - REPO_URL=https://github.com/gap-packages/liealgdb # A database of Lie algebras
    - REPO_URL=https://github.com/gap-packages/liepring # Database and algorithms for Lie p-rings
    - REPO_URL=https://github.com/gap-packages/loops # Computing with quasigroups and loops in GAP
    - REPO_URL=https://github.com/gap-packages/lpres # L-Presentations in GAP
    - REPO_URL=https://github.com/gap-packages/MapClass # Mapclass - a GAP Package For Mapping Class Orbit Computation
    - REPO_URL=https://github.com/hulpke/matgrp
    - REPO_URL=https://github.com/gap-packages/MathInTheMiddle # MitM interface functionality for GAP
    - REPO_URL=https://github.com/gap-packages/matrixss # Schreier-Sims for Matrix Groups
    - REPO_URL=https://github.com/gap-packages/meataxe64 # A new implementation of the MeatAxe algorithm
    - REPO_URL=https://github.com/gap-packages/Memoisation # Shared Persistent Memoisation Library
    - REPO_URL=https://github.com/gap-packages/modisom # Computing automorphisms and checking isomorphisms for modular group algebras of finite p-groups
    - REPO_URL=https://github.com/pjastr/NoCK
    - REPO_URL=https://github.com/gap-packages/NormalizInterface # A package for using normaliz from within GAP
    - REPO_URL=https://github.com/gap-packages/nq # GAP package for Nilpotent Quotients of Finitely Presented Groups
    - REPO_URL=https://github.com/gap-packages/numericalsgps # A GAP package to deal with numerical semigroups and affine semigroups
    - REPO_URL=https://github.com/gap-packages/openmath # OpenMath functionality in GAP
    - REPO_URL=https://github.com/gap-packages/orb # The GAP package orb for advanced orbit enumerations
    - REPO_URL=https://github.com/gap-packages/OrbitalGraphs # GAP Computations with Orbital Graphs
    - REPO_URL=https://github.com/gap-packages/PatternClass # Exploring permutation pattern classes build by token passing networks
    - REPO_URL=https://github.com/gap-packages/permut # A package to deal with permutability in finite groups
    - REPO_URL=https://github.com/gap-packages/polenta # GAP package for polycyclic presentations for matrix groups
    - REPO_URL=https://github.com/gap-packages/polycyclic # Computation with polycyclic groups
    - REPO_URL=https://github.com/gap-packages/primgrp # GAP Primitive Groups Library
    - REPO_URL=https://github.com/gap-packages/profiling # GAP profiling output
    - REPO_URL=https://github.com/gap-packages/qaos # Interfacing the QaoS database from GAP
    - REPO_URL=https://github.com/gap-packages/qpa # GAP package for quivers and path algebras
    - REPO_URL=https://github.com/gap-packages/radiroot # Roots of a Polynomial as Radicals
    - REPO_URL=https://github.com/gap-packages/rcwa # Residue-Class-Wise Affine Groups
    - REPO_URL=https://github.com/gap-packages/recog # The GAP package recog to collect methods for constructive recognition
    - REPO_URL=https://github.com/gap-packages/RegisterPackageTNUMDemo # Demo package for RegisterTNUM
    - REPO_URL=https://github.com/gap-packages/resclasses # Set-Theoretic Computations with Residue Classes
    - REPO_URL=https://github.com/gap-packages/scscp # Symbolic Computation Software Composability Protocol in GAP
    - REPO_URL=https://github.com/gap-packages/Semigroups # The GAP package Semigroups
    - REPO_URL=https://github.com/gap-packages/semirings # Semiring functionality for GAP
    - REPO_URL=https://github.com/gap-packages/sglppow # Database of groups of prime-power order for some prime-powers
    - REPO_URL=https://github.com/gap-packages/sgpdec # GAP package for Hierarchical Composition and Decomposition of Permutation Groups and Transformation Semigroups
    - REPO_URL=https://github.com/gap-packages/sgpviz # A GAP package for visualizing finite semigroups
    - REPO_URL=https://github.com/simpcomp-team/simpcomp
    - REPO_URL=https://github.com/gap-packages/singular # A GAP interface to Singular
    - REPO_URL=https://github.com/gap-packages/SingularInterface # A GAP package for accessing Singular from within GAP
    - REPO_URL=https://github.com/gap-packages/smallgrp # The GAP Small Groups Library
    - REPO_URL=https://github.com/gap-packages/sonata # System of nearrings and their applications
    - REPO_URL=https://github.com/gap-packages/sophus # Computing in nilpotent Lie algebras
    - REPO_URL=https://github.com/gap-packages/subsemi # GAP package for enumerating subsemigroups of semigroups by several different search algorithms.
    - REPO_URL=https://github.com/vlaver/Thelma
    - REPO_URL=https://github.com/gap-packages/tomlib
    - REPO_URL=https://github.com/gap-packages/toric # toric is a GAP package (gap-system.org) for doing computations with toric varieties.
    - REPO_URL=https://github.com/hulpke/transgrp
    - REPO_URL=https://github.com/gap-packages/unipot # Computing with elements of unipotent subgroups of Chevalley groups
    - REPO_URL=https://github.com/gap-packages/unitlib # UnitLib - library of normalized unit groups of modular group algebras
    - REPO_URL=https://github.com/gap-packages/utils # GAP package utils - utility functions collected from other packages
    - REPO_URL=https://github.com/gap-packages/uuid # Provide RFC4122 UUIDs
    - REPO_URL=https://github.com/gap-packages/walrus # Computational Methods for Finitely Generated Monoids and Groups
    - REPO_URL=https://github.com/gap-packages/wedderga # Wedderburn Decomposition of Group Algebras
    - REPO_URL=https://github.com/gap-packages/xmod # GAP package XMod (Crossed Modules and Cat1-Groups) 
    - REPO_URL=https://github.com/gap-packages/xmodalg # GAP package XModAlg (Crossed Modules and Cat1-Algebras)
    - REPO_URL=https://github.com/gap-packages/YangBaxter # Set-theoretic solutions of the Yang-Baxter equation
    - REPO_URL=https://github.com/gap-packages/ZeroMQInterface # GAP Bindings to ZeroMQ

services:
  - docker

before_install:
- docker pull ${GAPCONTAINER}

script:
    - docker version
    - docker run -v $PWD:/home/gap/travis/ ${GAPCONTAINER} /bin/sh -c "GAPDIRNAME=${GAPDIRNAME} REPO_URL=${REPO_URL} TERM=xterm LANG=en_GB.UTF-8 /home/gap/travis/ci.sh"
